# Generated by Django 3.1.1 on 2020-10-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201011_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user_id',
            new_name='user',
        ),
    ]
