# Generated by Django 3.1.1 on 2020-10-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201010_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
