# Generated by Django 3.1.1 on 2020-10-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201011_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
