# Generated by Django 3.1.1 on 2020-11-14 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201113_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='_user_follower_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
