# Generated by Django 3.1.1 on 2020-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropicanna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tropicanna.Flavor'),
        ),
    ]
