# Generated by Django 3.1.1 on 2020-12-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tropicanna', '0002_category_flavors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
